## wsl {{{
# https://superuser.com/questions/1749781/how-can-i-check-if-the-environment-is-wsl-from-a-shell-script
if [ -f /proc/sys/fs/binfmt_misc/WSLInterop ]; then
  # alias for .exe utilities
  if hash wezterm.exe 2>/dev/null; then
    alias wezterm=wezterm.exe 
  fi
fi
## }}}

