#!/usr/bin/env sh

# Description: Quickly navigate to target directory.
#
# Dependencies: fzf, fd
#
# Inspired on fzcd by Dave Snider https://www.youtube.com/watch?v=-knZwdd1ScU
#
# Shell: POSIX compliant
# Author: Guilherme Zagatti

. "$(dirname "$0")"/.nnn-plugin-helper

if [ "$(cmd_exists fzf)" -eq "0" ]; then
  sel=$(fd . $HOME ./ --type d | awk "{gsub(\"$HOME\",\"~\")}1" | fzf)
else
  exit 1
fi

if [ -n "$sel" ]; then
  sel=$(echo $sel | awk "{gsub(\"~\",\"$HOME\")}1")
  if ! [ -d "$sel" ]; then
    sel=$(dirname "$sel")
  elif [ "$sel" = "." ]; then
    exit 0
  fi

  # check if selected path returned
  # by fzf command is absolute
  case $sel in
    /*)
      nnn_cd "$sel" ;;
    *)
      # remove "./" prefix if it exists
      sel="${sel#./}"
      if [ "$PWD" = "/" ]; then
        nnn_cd "/$sel"
      else
        nnn_cd "$PWD/$sel"
      fi ;;
  esac

fi
