#!/usr/bin/env sh

# Description: Quickly navigate to target directory.
#
# Dependencies: fzf, fd
#
# Inspired on fzcd by Dave Snider https://www.youtube.com/watch?v=-knZwdd1ScU
#
# Shell: POSIX compliant
# Author: Guilherme Zagatti

# detect whether hidden files are active in nnn
# not sure how to capture this information
# INCLUDE_HIDDEN="${INCLUDE_HIDDEN:-0}"

if [ "$PWD" = "$HOME" ]; then
  DIRS="$HOME"
else
  DIRS="$HOME ./"
fi

if [ "$THEME" = "leuven" ]; then
    COLOR="--color=light"
elif [ "$THEME" = "dracula" ]; then
    COLOR="--color=dark"
else
    COLOR="--no-color"
fi

. "$(dirname "$0")"/.nnn-plugin-helper

if [ "$(cmd_exists fzf)" -eq "0" ]; then
  # if [ "$INCLUDE_HIDDEN" -eq 0 ]; then
    sel=$(fd . $DIRS --type d | awk "{gsub(\"$HOME\",\"~\")}1" | fzf $COLOR)
  # else
  #   sel=$(fd . $DIRS ./ --type d -H | awk "{gsub(\"$HOME\",\"~\")}1" | fzf $COLOR)
  # fi
else
  exit 1
fi

if [ -n "$sel" ]; then
  sel=$(echo $sel | awk "{gsub(\"~\",\"$HOME\")}1")
  if ! [ -d "$sel" ]; then
    sel=$(dirname "$sel")
  elif [ "$sel" = "." ]; then
    exit 0
  fi

  # check if selected path returned
  # by fzf command is absolute
  case $sel in
    /*)
      nnn_cd "$sel" ;;
    *)
      # remove "./" prefix if it exists
      sel="${sel#./}"
      if [ "$PWD" = "/" ]; then
        nnn_cd "/$sel"
      else
        nnn_cd "$PWD/$sel"
      fi ;;
  esac

fi
