# https://man.cx/latexmk
# causes trouble when latex is updating and there are scaffolding files
# $cleanup_mode=2;
$clean_ext="out bbl fdb_latexmk run.xml synctex* _minted-%R/* _minted-%R";
$latex="latex --shell-escape -synctex=1 %O %S";
$pdflatex="pdflatex --shell-escape -synctex=1 %O %S";
$lualatex="lualatex --shell-escape -synctex=1 %O %S";
